# Backbone
#backbone: resnet50
backbone: densenet
#backbone: ghostnet
#backbone: mobilenetv1
#backbone: mobilenetv2

# Transfer loss related
transfer_loss_weight: 0.5
transfer_loss: mmd

# Optimizer related
lr: 0.01
weight_decay: 0.0005
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
n_iter_per_epoch: 100
n_epoch: 50

# Others
seed: 1
num_workers: 3
